name: Oh Eye Dee See
on:
  workflow_dispatch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      id: checkout-repository
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: actions/github-script@v7
      id: id-provider-script-get-token-url
      timeout-minutes: 10
      with:
        debug: true
        script: |
          const token = process.env['ACTIONS_RUNTIME_TOKEN']
          const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
          core.setOutput('TOKEN', token.trim())
          core.setOutput('IDTOKENURL', runtimeUrl.trim())
    - id: id-provider-get-idtoken    
      run: |
        IDTOKEN=$(curl -H "Authorization: Bearer ${{steps.id-provider-script-get-token-url.outputs.TOKEN}}" ${{steps.id-provider-script-get-token-url.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
        echo $IDTOKEN
        jwtd() {
            if [[ -x $(command -v jq) ]]; then
                jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
            fi
        }
        jwtd $IDTOKEN
        echo "idToken=${IDTOKEN}" >> $GITHUB_OUTPUT
      
    - id: print-id-token-temp
      uses: actions/github-script@v7
      timeout-minutes: 10
      with:
        debug: true
        script: |
          const token = "${{ steps.id-provider-get-idtoken.outputs.IDTOKEN }}"
          token_arr = token.split(".")
          console.log("printing the header")
          console.log(token_arr[0].substr(1))
          console.log("printing the token")
          console.log(token_arr)

    - id: authenticator-resource-run-service
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "compose.yml"
         env:
          JWT_SIGNING_SECRET: "${{ secrets.jwtSigningSecret }}"
    
    - id: authenticator-get-access-token
      run: |
        ACCESS_TOKEN=$(curl -X POST -H "Authorization: Bearer ${{steps.id-provider-get-idtoken.outputs.idToken}}" http://localhost:8081/token | jq -r '.access_token')
        echo "accessToken=${ACCESS_TOKEN}" >> $GITHUB_OUTPUT

    - id: resource-server
      run: |
        curl -X GET -H "Authorization: Bearer ${{ steps.authenticator-get-access-token.outputs.accessToken}}" http://localhost:8081/org/svivekkrishna
        